"""Generate local executable launchers without changing application or user config."""

import shlex
import sys
from .config import ROOT


def main():
    """Install only scripts inside this source directory, using the current Python."""
    directory = ROOT / "bin"
    directory.mkdir(exist_ok=True)
    scripts = {
        "codex-bridge": "",
        "Launch Codex Bridge.command": "--desktop-launch",
        "Launch Standard Codex.command": "--desktop-launch --standard",
    }
    for name, args in scripts.items():
        path = directory / name
        path.write_text(
            "#!/bin/sh\n# Generated by python3 -m bridge.install.\n"
            f"exec {shlex.quote(sys.executable)} {shlex.quote(str(ROOT / 'run_bridge.py'))} {args} \"$@\"\n"
        )
        path.chmod(0o755)
    print("Created local launchers in " + str(directory))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
